### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by janvernieuwe** [Haamcdevs/haamcbot#47]
- [ ] Remove unused config values
- [ ] Remove .sh script, you can just run `python -u discordpy.py` and on the VPS is in supervisor

**Comment by janvernieuwe** [comment]
Also improve the handling of this exception:
```
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/root/haamcbot/cogs/channels.py", line 211, in join
    await message.add_user(user)
  File "/home/root/haamcbot/cogs/channels.py", line 69, in add_user
    await channel.send(f":inbox_tray: {user.mention} joined")
  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 856, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```
